Title: Flora Time Tracker
NavigationHome: Home
NavigationTryFree: Try for free
NavigationSignUp: Sign up
NavigationSignIn: Sign in

SplashHead: A simple time tracker
SplashSubHead: Track the time you spent on tasks effortlessly.
SplashButton: Get Started

FeaturesHead: Features
FeaturesTimeTrackingHead: Time Tracking
FeaturesTimeTrackingContent: Easily track the time spent on tasks of different projects.
FeaturesReportingHead: Reporting
FeaturesReportingContent: Generate HTML or CSV reports to send to your manager or client.
FeaturesDashboardHead: Friendly Dashboard
FeaturesDashboardContent: Different types of charts providing an overview of the tracked time and earned income.
FeaturesOpenSourcedHead: Open Source
FeaturesOpenSourcedContent: Contribute with the project or fork and customize it for your needs.

RibbonHead: No account needed.
RibbonContent: By using an unique url you can access your workspace and start tracking time without the need to create an account.
RibbonTryForFree: Try for free

MoreInfoHead: More information
MoreInfoFormName: Your Name
MoreInfoFormNamePlaceHolder: Your Name
MoreInfoFormEmail: Your Email
MoreInfoFormEmailPlaceHolder: Your Email
MoreInfoFormMessage: Your message
MoreInfoFormMessagePlaceHolder: Write your message
MoreInfoFormSend: Send message

MoreInfoContributionHead: Contributions Policy
MoreInfoContributionContent: The project is hosted on github and everyone are welcome to open pull requests for bug fixing or for implementation of new features.

MoreInfoDonationsHead: Donations
MoreInfoDonationsContent: You can also donate to support the project and contribute with.
MoreInfoDonationsButton20: Donate 20.00
MoreInfoDonationsButton30: Donate 30.00
MoreInfoDonationsButton40: Donate 40.00
MoreInfoDonationsButton50: Donate 50.00
