Title: Flora Rastreador de Tempo
NavigationHome: Início
NavigationTryFree: Teste de graça
NavigationSignUp: Assine
NavigationSignIn: Acesse

SplashHead: Um simples rastreador de tempo
SplashSubHead: Rastreia de maneira fácil o tempo que você gasta em tarefas.
SplashButton: Use agora

FeaturesHead: Funcionalidades
FeaturesTimeTrackingHead: Rastreador de Tempo
FeaturesTimeTrackingContent: Rastreia de maneira fácil o tempo gasto em tarefas de diferentes projetos.
FeaturesReportingHead: Relatórios
FeaturesReportingContent: Gere relatórios em HTML ou CSV para enviar para gerentes e clientes.
FeaturesDashboardHead: Painel de Gráficos
FeaturesDashboardContent: Diferentes tipos de gráficos fornecem uma imagem do tempo rastreado e do dinheiro recebido.
FeaturesOpenSourcedHead: Código Aberto
FeaturesOpenSourcedContent: Contribua com o projeto ou customize para as suas necessidades.

RibbonHead: Não é necessário ter conta
RibbonContent: Ao usar uma URL única, você pode acessar a sua área de trabalho e começar a rastrear o tempo gasto em suas tarefas sem a necessidade de criar uma conta.
RibbonTryForFree: Teste de graça

MoreInfoHead: Mais informações
MoreInfoFormName: Nome
MoreInfoFormNamePlaceHolder: Digite seu nome.
MoreInfoFormEmail: Email
MoreInfoFormEmailPlaceHolder: Digite seu email
MoreInfoFormMessage: Mensagem
MoreInfoFormMessagePlaceHolder: Escreva sua mensagem
MoreInfoFormSend: Enviar mensagem

MoreInfoContributionHead: Política de Contribuição
MoreInfoContributionContent: O projeto está hospedado no github e qualquer um é bem-vindo à abrir pull requests para a correção de bugs ou implementação de novas funcionalidades.

MoreInfoDonationsHead: Doações
MoreInfoDonationsContent: Você também pode contribuir doando valores para ajudar a manter o projeto.
MoreInfoDonationsButton20: Doe 20.00
MoreInfoDonationsButton30: Doe 30.00
MoreInfoDonationsButton40: Doe 40.00
MoreInfoDonationsButton50: Doe 50.00
